# Generated by Django 5.2 on 2025-06-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_category_remove_student_enrolled_courses_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='courses.category'),
        ),
    ]
