# Generated by Django 5.2 on 2025-08-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
    ]
